export const languages = {
  ru: {
    days: [
      'понедельник',
      'вторник',
      'среда',
      'четверг',
      'пятница',
      'суббота',
      'воскресенье',
    ],
    months: [
      'январь',
      'февраль',
      'март',
      'апрель',
      'май',
      'июнь',
      'июль',
      'август',
      'сентябрь',
      'октябрь',
      'ноябрь',
      'декабрь',
    ],
  },
  fr: {
    days: [
      'Lundi',
      'Mardi',
      'Mercredi',
      'Jeudi',
      'Vendredi',
      'Samedi',
      'Dimanche',
    ],
    months: [
      'janvier',
      'février',
      'mars',
      'avril',
      'mai',
      'juin',
      'juillet',
      'août',
      'septembre',
      'octobre',
      'novembre',
      'décembre',
    ],
  },
};

export const events = [
  {
    title: 'New Year’s Day',
    starts: new Date('2018', '0', '01'),
    color: '#b342f4',
    calendar: 'Publick Holidays',
  },
  {
    title: 'Friday	Good Friday',
    starts: new Date('2018', '02', '30'),
    color: '#b342f4',
    calendar: 'Publick Holidays',
  },
  {
    title: 'Easter Monday',
    starts: new Date('2018', '03', '02'),
    color: '#b342f4',
    calendar: 'Publick Holidays',
  },
  {
    title: 'Early May bank holiday',
    starts: new Date('2018', '04', '07'),
    color: '#b342f4',
    calendar: 'Publick Holidays',
  },
  {
    title: 'Spring bank holiday',
    starts: new Date('2018', '04', '28'),
    color: '#b342f4',
    calendar: 'Publick Holidays',
  },
  {
    title: 'Summer bank holiday',
    starts: new Date('2018', '07', '27'),
    color: '#b342f4',
    calendar: 'Publick Holidays',
  },
  {
    title: 'Christmas Day',
    starts: new Date('2018', '11', '25'),
    color: '#b342f4',
    calendar: 'Publick Holidays',
  },
  {
    title: 'Boxing Day',
    starts: new Date('2018', '11', '26'),
    color: '#b342f4',
    calendar: 'Publick Holidays',
  },
];
